# Generated by Django 5.0.6 on 2024-07-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionviajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
